name: 'Looker Marketplace Spectacles Tests'
description: 'Spectacles Tests to verify Looker Marketplace Project Block assets'
env:
  LOOKER_BASE_URL: ${{secrets.LOOKER_BASE_URL}}
  LOOKER_CLIENT_ID: ${{secrets.LOOKER_CLIENT_ID}}
  LOOKER_CLIENT_SECRET: ${{secrets.LOOKER_CLIENT_SECRET}}
runs:
  using: 'node16'
  main: 'dist/index.js'